### PR TITLE
Adding error message to diskspd when it cannot open one of the entropy files.

### PR DESCRIPTION
**Pull request by bdenison99**

### CODE REVIEW

**Comment by dl2n** [comment]
Bart, by default I think I want to keep .gitignore (this is the std one the folks here gave me to keep things like VS compilation artifacts out of git's view). Was this causing problems for you?

**Comment by bdenison99** [comment]
No it wasn't - the tool I was using just wouldn't let me unselect it.

Date: Fri, 22 Apr 2016 17:20:36 -0700

**Comment by bdenison99** [comment]
Please delete this pull request if you can.  I will submit a new one with the .gitignore file removed.

**Comment by dl2n** [comment]
Closing, Bart created a new pull w/o .gitignore

**Pull request closed without merging**
