### PR TITLE
Update to add .\ to eliminate errors on run.

### PR DESCRIPTION
**Pull request by PhilipElder**
Fix for the red ink. :)

### CODE REVIEW

**Comment by PhilipElder** [comment]
Dan,
Then I must be missing something? I checked the documentation and it states that that variable gets updated during the script's install routine. Am I supposed to log off and back on again for that to take?

**Comment by dl2n** [comment]
If you're running on the same node that you ran install-vmfleet on, I'm confused - it should be working. Look at $env:path. If you absolutely have to, you can just add it like this:

$env:path += ';c:\clusterstorage\collect\control'

**Comment by PhilipElder** [comment]
Okay, I have a brand new Kepler-47B series cluster that I need to burn-in before flattening and setting it up on our client's domain. I'll give it a shot and let you know.

**Comment by PhilipElder** [comment]
Okay, confirmed. For some reason $env:path does not show the indicated path you have.

I started another PoSh session, added it there, and went back to my original only to find the path statement looks to be shell specific? :)

It looks to be working now.

**Pull request closed without merging**
