### PR TITLE
Generate .csv output for the XMLs

### PR DESCRIPTION
**Pull request by iinfi1**
This file generates a .csv output for the XMLs in the result folder. Ensure that you have only the XMLs of the last run in the results folder.
generate-output.ps1 | export-csv [path-to-csv]

### CODE REVIEW

**Comment by dl2n** [comment]
Howdy,

I’m curious if you can help us understand what you’re looking for with this variant on process-diskspd? I think it would be easier to keep all of this within one tool.

If you find emitting the rows as objects useful that would be fairly straightforward; so would parameterizing the use of a different field separator. The reason it uses <tab> is that that is unambiguous in the face of fields which could potentially contain commas. It’s a convention used by SQL import tools.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by iinfi1** [comment]
My intent of this script generate-output.ps1, is to collate the IOPs
results from all the XMLs in the results folder to a CSV file. A sample
ouput of the CSV file is attached.

This is just a script to display the output of the previous vmfleet or
diskspd runs.

thanks,
Arvind

**Comment by dl2n** [comment]
Have you looked at process-diskspd.ps1?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by iinfi1** [comment]
Wow. I had not see that script. Thats useful. Sorry for the inconvenience.

Thanks,
Arvind

**Comment by dl2n** [comment]
Great. I’ll decline this specific push request, but feel free to ping in with ideas.

Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dl2n** [comment]
Per discussion, lets see if we can convert this into feedback on process-diskspd.ps1.

**Pull request closed without merging**
